// ---------------------------------------------------------------------------
// Catalogue : une entrée = une page /produit/<slug>/ + une carte tarif.
//
// resaId : identifiant du produit dans Resamare (widget calendrier). Absent →
//          la réservation se fait par téléphone.
// note   : note et nombre d'avis affichés par l'ancienne boutique WooCommerce,
//          repris à l'identique pour conserver les étoiles dans Google.
// title / description : balises SEO de l'ancienne page (coquilles corrigées).
// ---------------------------------------------------------------------------

export const categories = {
  parachute: { nom: "Parachute ascensionnel", page: "/parachute-ascensionnel/" },
  jetski: { nom: "Jet Ski", page: "/location-jet-ski/" },
  randonnee: { nom: "Randonnée Jet Ski", page: "/randonnee-jet-ski/" },
  bouee: { nom: "Bouée tractée", page: "/bouee-tractee/" },
  wakeboard: { nom: "Wakeboard", page: "/wakeboard/" },
  wakesurf: { nom: "Wakesurf", page: "/wakeboard/" },
  ski: { nom: "Ski nautique", page: "/ski-nautique/" },
  packs: { nom: "Packs", page: "/nos-packs/" },
};

/** Blocs communs aux fiches produit. */
const JET_SKI_COMMENT = [
  "À votre arrivée sur la base nautique, vous assistez à un briefing qui vous explique le fonctionnement de la machine et la réglementation sur l’eau.",
  "Vous partez ensuite sur votre jet ski : carburant, équipement et assurance compris !",
  "Accessible à partir de 16 ans (autorisation parentale obligatoire pour les mineurs). Pièces d’identité obligatoires pour tous les conducteurs.",
];
const PARACHUTE_POINTS = [
  "Pas besoin de savoir nager : il n’y a aucun moment dans l’eau.",
  "Les mains complètement libres pendant la totalité du vol.",
  "Le vol s’effectue en maillot ou habillé.",
  "Décollage et atterrissage sur la plateforme du bateau.",
  "Pas de sensation de vertige : vous n’avez aucun contact direct avec le sol.",
];
const GLISSE_POINTS = [
  "Encadré par un moniteur breveté d’État.",
  "Sessions le matin de préférence, quand la mer est calme.",
  "Des conseils de qualité : votre pilote est un vrai pro de la glisse.",
];
const RANDONNEE_DESTINATIONS = [
  {
    titre: "En direction de l’Esterel",
    texte: "Site volcanique remarquable du littoral de la Côte d’Azur : le rouge flamboyant des roches plonge dans le bleu intense de la mer, entre collines de maquis, criques secrètes et impressionnantes calanques.",
  },
  {
    titre: "En direction des îles de Lérins",
    texte: "Un cadre idyllique à la nature préservée, où les piscines d’eau turquoise côtoient les pins parasols. Les deux îles mêlent une faune et une flore uniques aux mystères du Masque de fer et à la quiétude des moines cisterciens.",
  },
];

export const produits = [
  // --- Parachute ------------------------------------------------------------
  {
    slug: "parachute-ascensionnel",
    nom: "Parachute Ascensionnel",
    categorie: "parachute",
    prix: 50,
    prixMin: 40,
    unite: "par personne",
    age: "Plus de 13 ans",
    resaId: "2003",
    note: { valeur: 5, nombre: 152 },
    images: ["parachute-vol-ciel", "parachute-trois-amies", "parachute-atterrissage"],
    title: "Parachute Ascensionnel - Mandelieu WaterSports",
    description: "Découvrez le parachute ascensionnel jusqu'à 5 personnes à Mandelieu, Théoule. Venez entre amis, en couple ou en famille profiter du parachute ascensionnel.",
    accroche: "Envolez-vous jusqu’à 5 personnes en même temps et admirez un panorama à 360° entre ciel et mer.",
    texte: [
      "Envolez-vous pour de nouvelles sensations et admirez un panorama à 360° entre ciel et mer avec vos amis, vos enfants, vos parents. Décollage et retour en douceur sur le bateau : vous vous sentirez en sécurité.",
      "Vous rêvez de découvrir la baie de Mandelieu et de Cannes comme vous ne l’avez jamais vue ? Embarquez à bord de notre bateau plateforme nouvelle génération, avec un pilote expérimenté breveté d’État : la vue est à couper le souffle.",
    ],
    points: PARACHUTE_POINTS,
    pointsTitre: "À partir de 3 ans pour la pratique du parachute ascensionnel",
  },
  {
    slug: "parachute-ascensionnel-enfant",
    nom: "Parachute Ascensionnel Enfant",
    categorie: "parachute",
    prix: 40,
    unite: "par personne",
    age: "Entre 3 et 12 ans",
    resaId: "2003",
    note: { valeur: 5, nombre: 220 },
    images: ["parachute-famille", "parachute-carte-enfant", "parachute-fou-rire"],
    title: "Parachute Ascensionnel Enfant - Mandelieu WaterSports",
    description: "Le parachute ascensionnel pour les enfants de 3 à 12 ans à Mandelieu, Théoule. Un vol en famille, jusqu'à 5 personnes sous la même voile, en toute sécurité.",
    accroche: "Un premier vol inoubliable pour les enfants de 3 à 12 ans, accompagnés d’un adulte.",
    texte: [
      "Envolez-vous en famille pour de nouvelles sensations et admirez un panorama à 360° entre ciel et mer. Décollage et retour en douceur sur la plateforme du bateau : les enfants se sentent en sécurité du début à la fin.",
      "Jusqu’à 5 personnes volent sous la même voile : parents et enfants partagent le même moment, au-dessus de la baie de Mandelieu, Cannes et Théoule-sur-Mer.",
    ],
    points: PARACHUTE_POINTS,
    pointsTitre: "Un vol pensé pour les enfants",
  },

  // --- Location jet ski -------------------------------------------------------
  {
    slug: "location-jet-ski-30-minutes",
    nom: "Location Jet Ski 30 minutes",
    categorie: "jetski",
    prix: 90,
    unite: "par jet ski",
    duree: "PT30M",
    dureeTexte: "30 minutes",
    age: "Dès 16 ans",
    resaId: "2005",
    note: { valeur: 5, nombre: 912 },
    images: ["carte-location-30", "jet-ski-duo-baie", "jet-ski-pilote"],
    title: "Location Jet Ski 30 minutes Cannes Mandelieu | Watersports",
    description: "Louez un jet ski 30 minutes à Cannes, Mandelieu. Venez entre amis, en couple ou en famille profiter de la baie de Cannes en jet ski à Mandelieu et Cannes",
    accroche: "Trente minutes de navigation libre dans la baie de Mandelieu, sans permis bateau. Seul ou à deux, même tarif.",
    texte: [
      "Le jet ski ne manquera pas de faire le bonheur des amateurs de sensations fortes. L’activité est accessible avec ou sans permis grâce à la présence de votre moniteur diplômé BPJEPS.",
      "Seul, entre amis ou en famille, partez à la découverte de la magnifique baie de la Rague. Après un briefing sur la pratique et le maniement du scooter des mers, vous êtes équipé d’un gilet de sauvetage et vous débutez à votre rythme. Pour les plus sportifs, vient le moment de mettre les gaz !",
    ],
    encart: {
      titre: "Baladez-vous dans la baie de Cannes !",
      texte: "Un des plus beaux endroits à voir en jet ski. Les îles de Lérins sont aussi un lieu exceptionnel, accessible avec la location d’une heure. Nous vous donnons les meilleurs conseils pour profiter au maximum de votre location.",
    },
    comment: JET_SKI_COMMENT,
    horaires: "Venez quand vous voulez entre 9 h et 19 h.",
  },
  {
    slug: "location-jet-ski-45-minutes",
    nom: "Location Jet Ski 45 minutes",
    categorie: "jetski",
    prix: 120,
    unite: "par jet ski",
    duree: "PT45M",
    dureeTexte: "45 minutes",
    age: "Dès 16 ans",
    resaId: "2006",
    images: ["jet-ski-location-ponton", "jet-ski-duo-esterel", "jet-ski-femme-pilote"],
    title: "Location Jet Ski 45 minutes Cannes Mandelieu | Watersports",
    description: "Louez un jet ski 45 minutes à Cannes, Mandelieu. Venez entre amis, en couple ou en famille profiter de la baie de Cannes en jet ski à Mandelieu et Cannes",
    accroche: "Doublez le plaisir avec 45 minutes de jet ski sans permis, seul ou à deux au même tarif.",
    texte: [
      "Optez pour une session de 45 minutes, idéale pour décupler les sensations fortes au tarif le plus avantageux, seul ou à deux sur votre jet ski sans permis.",
      "Après un briefing avec votre moniteur diplômé d’État, vous êtes équipé d’un gilet de sauvetage et vous partez à la découverte de la baie de la Rague, jusqu’aux premières criques de l’Esterel.",
    ],
    encart: {
      titre: "Baladez-vous dans la baie de Cannes !",
      texte: "Un des plus beaux endroits à voir en jet ski. Nous vous donnons les meilleurs conseils pour profiter au maximum de votre location de jet ski.",
    },
    comment: JET_SKI_COMMENT,
    horaires: "Venez quand vous voulez entre 9 h et 19 h.",
  },
  {
    slug: "location-jet-ski-1-heure",
    nom: "Location Jet Ski 1 heure",
    categorie: "jetski",
    prix: 160,
    unite: "par jet ski",
    duree: "PT1H",
    dureeTexte: "1 heure",
    age: "Dès 16 ans",
    resaId: "2007",
    note: { valeur: 5, nombre: 897 },
    images: ["carte-location-1h", "jet-ski-femme-pilote", "jet-ski-duo-esterel"],
    title: "Location Jet Ski 1 heure Cannes Mandelieu | Watersports",
    description: "Louez un jet ski 1h à Cannes, Mandelieu. Venez entre amis, en couple ou en famille profiter de la baie de Cannes en jet ski à Mandelieu et Cannes",
    accroche: "Une heure de liberté en jet ski sans permis, jusqu’aux îles de Lérins. Seul ou à deux, même tarif.",
    texte: [
      "Le jet ski ne manquera pas de faire le bonheur des amateurs de sensations fortes. L’activité est accessible avec ou sans permis grâce à la présence de votre moniteur diplômé BPJEPS.",
      "Une heure, c’est le temps idéal pour pousser jusqu’aux îles de Lérins ou longer la côte de l’Esterel. Après le briefing, vous êtes équipé d’un gilet de sauvetage et vous partez à votre rythme.",
    ],
    encart: {
      titre: "Cap sur les îles de Lérins !",
      texte: "Les îles de Lérins sont un lieu exceptionnel à voir en jet ski, accessible uniquement avec la location d’une heure. Nous vous donnons les meilleurs conseils d’itinéraire avant le départ.",
    },
    comment: JET_SKI_COMMENT,
    horaires: "Venez quand vous voulez entre 9 h et 19 h.",
  },

  // --- Randonnées jet ski ---------------------------------------------------
  {
    slug: "randonnee-jet-ski-coucher-de-soleil",
    nom: "Randonnée Jet Ski Coucher de soleil (1h)",
    categorie: "randonnee",
    prix: 130,
    unite: "par jet ski",
    duree: "PT1H",
    dureeTexte: "Plus d’1 heure",
    age: "Dès 16 ans",
    resaId: "2000",
    note: { valeur: 5, nombre: 688 },
    bestSeller: true,
    images: ["jet-ski-coucher-soleil", "carte-randonnee-coucher-soleil", "jet-ski-sunset"],
    title: "Randonnée Jet Ski Coucher de soleil (1h) Cannes Mandelieu",
    description: "Randonnée coucher de soleil jet ski à Cannes, Mandelieu. Venez entre amis, en couple ou en famille profiter de la baie de Cannes en jet ski à Mandelieu",
    accroche: "Criques secrètes, calanques, eaux turquoises… et le soleil qui embrase l’Esterel.",
    sousTitre: "Randonnée jet ski coucher de soleil – Massif de l’Esterel",
    texte: [
      "Plongez dans une palette de couleurs éblouissantes avec notre randonnée jet ski coucher de soleil dans le massif de l’Esterel. Cette excursion crépusculaire de plus d’une heure promet une expérience inégalée.",
      "Imaginez-vous sur un jet ski, traversant les eaux calmes tandis que le soleil embrase le ciel et teinte l’horizon de nuances éclatantes. Explorez les paysages mystérieux et les criques cachées de l’Esterel, joyau secret de la Côte d’Azur.",
      "Accessible dès 16 ans, en solo ou en duo : alternez la conduite avec votre partenaire. Carburant, équipement de qualité et assurance sont inclus. L’heure de rendez-vous se fixe avec la base nautique selon la saison.",
    ],
    comment: JET_SKI_COMMENT,
    destinations: RANDONNEE_DESTINATIONS,
    horaires: "Rendez-vous à définir avec la base nautique en fonction de la saison.",
  },
  {
    slug: "randonnee-midi",
    nom: "Randonnée du midi (1h)",
    categorie: "randonnee",
    prix: 130,
    unite: "par jet ski",
    duree: "PT1H",
    dureeTexte: "Plus d’1 heure",
    age: "Dès 16 ans",
    resaId: "2001",
    note: { valeur: 5, nombre: 1467 },
    images: ["carte-randonnee-midi", "jet-ski-randonnee-esterel", "esterel-roches-rouges"],
    title: "Randonnée du midi (1h) Cannes Mandelieu",
    description: "Randonnée midi jet ski à Cannes, Mandelieu. Venez entre amis, en couple ou en famille profiter de la baie de Cannes en jet ski à Mandelieu",
    accroche: "L’Esterel sous le soleil de midi : falaises rouges, criques sauvages et pause baignade.",
    sousTitre: "Randonnée jet ski midi – Massif de l’Esterel",
    texte: [
      "Partez à la découverte du massif de l’Esterel avec notre randonnée jet ski du midi. Cette excursion de plus d’une heure vous fait profiter des paysages emblématiques de la Côte d’Azur sous une lumière éclatante.",
      "Au guidon de votre jet ski sans permis, naviguez sur les eaux turquoise entre criques sauvages, roches rouges et panoramas spectaculaires. Entre vitesse, baignade et paysages uniques, une sortie conviviale et rafraîchissante en pleine journée.",
      "Accessible dès 16 ans, en solo ou en duo. Carburant, équipement de qualité et assurance inclus. Rendez-vous à 11 h 30 pour un départ à midi.",
    ],
    comment: JET_SKI_COMMENT,
    destinations: RANDONNEE_DESTINATIONS,
    horaires: "Rendez-vous à 11 h 30 pour un départ à 12 h.",
  },
  {
    slug: "randonnee-jet-ski-petit-dejeuner",
    nom: "Randonnée Jet Ski Petit Déjeuner (2h)",
    categorie: "randonnee",
    prix: 200,
    unite: "par jet ski",
    duree: "PT2H",
    dureeTexte: "2 heures",
    age: "Dès 16 ans",
    resaId: "2002",
    note: { valeur: 5, nombre: 428 },
    bestSeller: true,
    images: ["carte-randonnee-petit-dejeuner", "petit-dejeuner-ponton", "iles-lerins-saint-honorat"],
    title: "Randonnée Jet Ski Petit Déjeuner (2h) Cannes Mandelieu",
    description: "Randonnée petit déjeuner jet ski à Cannes, Mandelieu. Venez entre amis, en couple ou en famille profiter de la baie de Cannes en jet ski à Mandelieu",
    accroche: "Petit déjeuner face à la mer, puis deux heures de jet ski vers les îles de Lérins.",
    sousTitre: "Randonnée jet ski petit déjeuner – Îles de Lérins et massif de l’Esterel",
    texte: [
      "Commencez votre journée en beauté avec un petit déjeuner face à la mer sur notre ponton : café chaud, jus de fruits, croissants, pains au chocolat et assiette de fruits frais. Le moment idéal pour faire connaissance et recevoir le briefing de votre moniteur.",
      "Partez ensuite pour deux heures de déconnexion totale sur nos jet skis sans permis dernière génération. Plongez dans les eaux cristallines qui entourent les îles de Lérins et le massif de l’Esterel.",
      "Laissez-vous guider par nos moniteurs qualifiés, qui vous assurent une expérience sûre et mémorable dans la baie de Cannes – Mandelieu – Théoule-sur-Mer.",
    ],
    comment: JET_SKI_COMMENT,
    destinations: RANDONNEE_DESTINATIONS,
    horaires: "Rendez-vous à 8 h 30 à la base nautique pour un départ à 9 h.",
  },

  // --- Bouée tractée ------------------------------------------------------
  {
    slug: "bouee-tractee-adulte",
    nom: "Bouée Tractée Adulte",
    categorie: "bouee",
    prix: 25,
    unite: "par personne",
    age: "À partir de 10 ans",
    resaId: "2008",
    images: ["bouee-tractee-groupe", "bouee-tractee-vitesse", "bouee-canape"],
    title: "Bouée Tractée Adulte - Mandelieu WaterSports",
    description: "La bouée tractée adulte à Mandelieu, Théoule : jusqu'à 8 personnes sur la bouée, fous rires et sensations de vitesse entre amis ou en famille.",
    accroche: "Jusqu’à 8 personnes en même temps sur la bouée. Accrochez-vous bien, ça va secouer !",
    texte: [
      "Tractée par le bateau, la bouée vous apporte des sensations de vitesse et d’adrénaline intenses. Fous rires en perspective entre amis, en famille, pour un anniversaire ou un enterrement de vie de célibataire.",
      "Notre pilote adapte la vitesse à votre groupe, et notre équipe technique contrôle l’équipement et les conditions de mer pour votre sécurité.",
    ],
    encart: {
      titre: "Choisissez votre bouée en arrivant !",
      texte: "Deux modèles au choix : la bouée « canapé », plus facile, qui accueille jusqu’à 8 personnes, et la bouée « plate », un peu plus physique, jusqu’à 6 personnes.",
    },
    horaires: "Disponible sans réservation : venez directement à la base nautique.",
  },
  {
    slug: "bouee-tractee-enfant",
    nom: "Bouée Tractée Enfant",
    categorie: "bouee",
    prix: 20,
    unite: "par personne",
    age: "Entre 3 et 10 ans",
    resaId: "2008",
    images: ["bouee-tractee-famille", "bouee-tractee-joie", "bouee-tractee-mer"],
    title: "Bouée Tractée Enfant - Mandelieu WaterSports",
    description: "La bouée tractée pour les enfants de 3 à 10 ans à Mandelieu, Théoule. Vitesse adaptée, bateau piloté par un professionnel : fous rires garantis en famille.",
    accroche: "Les enfants adorent : vitesse adaptée à leur âge, fous rires garantis.",
    texte: [
      "Tractée par le bateau, la bouée procure des sensations de vitesse… adaptées aux plus jeunes. Notre pilote règle son allure au groupe pour que chacun profite en toute sécurité.",
      "Amusez-vous sur l’eau entre amis ou en famille, dans le cadre magnifique de la baie de Mandelieu – Théoule.",
    ],
    encart: {
      titre: "Choisissez votre bouée en arrivant !",
      texte: "La bouée « canapé » accueille jusqu’à 8 personnes et convient parfaitement aux enfants ; la bouée « plate », plus physique, jusqu’à 6 personnes.",
    },
    horaires: "Disponible sans réservation : venez directement à la base nautique.",
  },

  // --- Wakeboard ----------------------------------------------------------
  {
    slug: "wakeboard-tour-simple",
    nom: "Wakeboard Tour Simple",
    categorie: "wakeboard",
    prix: 35,
    unite: "par personne",
    age: "Tout âge",
    resaId: "2048",
    images: ["wakeboard", "wakesurf"],
    title: "Wakeboard Tour Simple Mandelieu | Mandelieu WaterSports",
    description: "Découvrez le wakeboard tour simple à Mandelieu, Théoule. Venez entre amis, en couple ou en famille profiter du wakeboard à Mandelieu, Théoule",
    accroche: "Un tour de wakeboard derrière le bateau, avec un pilote professionnel.",
    texte: [
      "Tracté par un bateau comme en ski nautique, mais en position « de côté » (comme en snowboard ou en skateboard), vous surfez la vague après quelques essais, voire tentez des sauts en prenant appui sur celle-ci.",
      "Le wakeboard est sans aucun doute un des sports de glisse aquatique les plus accessibles et les plus grisants. Un sport de glisse pour tous.",
    ],
    points: GLISSE_POINTS,
  },
  {
    slug: "wakeboard-lecon-enfant",
    nom: "Wakeboard Leçon Enfant",
    categorie: "wakeboard",
    prix: 45,
    unite: "par personne",
    age: "À partir de 10 ans",
    resaId: "2049",
    note: { valeur: 5, nombre: 320 },
    images: ["wakeboard", "ski-nautique-enfant"],
    title: "Wakeboard Leçon Enfant Mandelieu | Mandelieu WaterSports",
    description: "Découvrez le wakeboard leçon enfant à Mandelieu, Théoule. Venez entre amis, en couple ou en famille profiter du wakeboard à Mandelieu, Théoule",
    accroche: "Des progrès dès le premier tour avec un moniteur professionnel.",
    texte: [
      "Faites des progrès avec un moniteur professionnel dès votre premier tour. Il donne aux jeunes riders les clés pour sortir de l’eau, trouver l’équilibre et prendre confiance.",
      "Dans une ambiance conviviale, de l’initiation au perfectionnement : amusez-vous sur l’eau tout en apprenant.",
    ],
    points: GLISSE_POINTS,
  },
  {
    slug: "wakeboard-lecon-adulte",
    nom: "Wakeboard Leçon Adulte",
    categorie: "wakeboard",
    prix: 55,
    unite: "par personne",
    age: "À partir de 13 ans",
    resaId: "2049",
    note: { valeur: 5, nombre: 320 },
    images: ["wakeboard", "wakesurf"],
    title: "Wakeboard Leçon Adulte Mandelieu | Mandelieu WaterSports",
    description: "Découvrez le wakeboard leçon adulte à Mandelieu, Théoule. Venez entre amis, en couple ou en famille profiter du wakeboard à Mandelieu, Théoule",
    accroche: "Initiation ou perfectionnement : un moniteur breveté d’État rien que pour vous.",
    texte: [
      "Débutant, vous apprenez à sortir de l’eau et à tenir la vague. Plus avancé, votre pilote vous aide à maîtriser de nouveaux tricks.",
      "Le wakeboard procure des sensations de glisse très rapidement : dans une ambiance conviviale, progressez à votre rythme dans la baie de Mandelieu.",
    ],
    points: GLISSE_POINTS,
  },

  // --- Wakesurf -----------------------------------------------------------
  {
    slug: "wakesurf-tour-simple",
    nom: "Wakesurf Tour Simple",
    categorie: "wakesurf",
    prix: 35,
    unite: "par personne",
    age: "Tout âge",
    images: ["wakesurf", "wakeboard"],
    title: "Wakesurf Tour Simple Mandelieu | Mandelieu WaterSports",
    description: "Découvrez le wakesurf tour simple à Mandelieu, Théoule. Venez entre amis, en couple ou en famille profiter du wakesurf à Mandelieu, Théoule",
    accroche: "Surfez la vague du bateau, sans corde, dans la baie de Mandelieu.",
    texte: [
      "Tracté par un bateau puis lâché sur sa vague, vous surfez à l’arrière du bateau en position « de côté ». Après quelques essais, vous tenez la vague, voire tentez des sauts.",
      "Le wakesurf est sans aucun doute un des sports de glisse aquatique les plus accessibles et les plus grisants. Un sport de glisse pour tous.",
    ],
    points: GLISSE_POINTS,
    telephone: true,
  },
  {
    slug: "wakesurf-lecon-enfant",
    nom: "Wakesurf Leçon Enfant",
    categorie: "wakesurf",
    prix: 40,
    unite: "par personne",
    age: "Entre 3 et 10 ans",
    note: { valeur: 5, nombre: 153 },
    images: ["wakesurf", "wakeboard"],
    title: "Wakesurf Leçon Enfant Mandelieu | Mandelieu WaterSports",
    description: "Découvrez le wakesurf leçon enfant à Mandelieu, Théoule. Venez entre amis, en couple ou en famille profiter du wakesurf à Mandelieu, Théoule",
    accroche: "Une leçon de wakesurf adaptée aux enfants, avec un moniteur breveté d’État.",
    texte: [
      "Faites des progrès avec un moniteur professionnel dès le premier tour. Il accompagne les enfants pas à pas pour se lever sur la planche et glisser dans le sillage du bateau.",
      "Fous rires en perspective : amusez-vous sur l’eau tout en apprenant.",
    ],
    points: GLISSE_POINTS,
    telephone: true,
  },
  {
    slug: "wakesurf-lecon-adulte",
    nom: "Wakesurf Leçon Adulte",
    categorie: "wakesurf",
    prix: 55,
    unite: "par personne",
    age: "À partir de 13 ans",
    note: { valeur: 5, nombre: 350 },
    images: ["wakesurf", "wakeboard"],
    title: "Wakesurf Leçon Adulte Mandelieu | Mandelieu WaterSports",
    description: "Découvrez le wakesurf leçon adulte à Mandelieu, Théoule. Venez entre amis, en couple ou en famille profiter du wakesurf à Mandelieu, Théoule",
    accroche: "Initiation ou perfectionnement au wakesurf avec un moniteur breveté d’État.",
    texte: [
      "Tracté par un bateau comme en ski nautique mais en position « de côté », vous apprenez à vous déplacer sur la vague à l’arrière du bateau, puis à la surfer sans corde.",
      "Dans une ambiance conviviale, de l’initiation au perfectionnement : le wakesurf, un sport de glisse pour tous.",
    ],
    points: GLISSE_POINTS,
    telephone: true,
  },

  // --- Ski nautique -------------------------------------------------------
  {
    slug: "ski-nautique-tour-simple",
    nom: "Ski Nautique Tour Simple",
    categorie: "ski",
    prix: 35,
    unite: "par personne",
    age: "Tout âge",
    resaId: "2048",
    images: ["ski-nautique", "ski-nautique-baie"],
    title: "Ski Nautique Tour Simple Mandelieu | Mandelieu WaterSports",
    description: "Découvrez le ski nautique tour simple à Mandelieu, Théoule. Venez entre amis, en couple ou en famille profiter du ski nautique à Mandelieu, Théoule",
    accroche: "Un tour de ski nautique dans la baie de Mandelieu, avec un pilote professionnel.",
    texte: [
      "Dès vos premiers tours, découvrez des sensations de glisse uniques avec le ski nautique : c’est le sport de glisse le plus rapide à assimiler !",
      "Tracté par un bateau en position « de face », vous skiez la vague après quelques essais, voire tentez des sauts en prenant appui sur celle-ci.",
    ],
    points: GLISSE_POINTS,
  },
  {
    slug: "ski-nautique-lecon-enfant",
    nom: "Ski Nautique Leçon Enfant",
    categorie: "ski",
    prix: 45,
    unite: "par leçon",
    age: "À partir de 10 ans",
    resaId: "2049",
    note: { valeur: 5, nombre: 730 },
    images: ["ski-nautique-enfant", "ski-nautique"],
    title: "Ski Nautique Leçon Enfant Mandelieu | Mandelieu WaterSports",
    description: "Découvrez le ski nautique leçon enfant à Mandelieu, Théoule. Venez entre amis, en couple ou en famille profiter du ski nautique à Mandelieu, Théoule",
    accroche: "Le ski nautique, le plus instinctif des sports de glisse : idéal pour débuter jeune.",
    texte: [
      "Dès les premiers tours, les enfants découvrent des sensations de glisse uniques : le ski nautique est le sport de glisse le plus rapide à assimiler.",
      "Leur moniteur les guide pour sortir de l’eau, garder l’équilibre et suivre le bateau en toute confiance. Réservez un créneau le matin, quand la mer est calme.",
    ],
    points: GLISSE_POINTS,
  },
  {
    slug: "ski-nautique-lecon-adulte",
    nom: "Ski Nautique Leçon Adulte",
    categorie: "ski",
    prix: 55,
    unite: "par personne",
    age: "À partir de 13 ans",
    resaId: "2049",
    note: { valeur: 5, nombre: 1140 },
    images: ["ski-nautique-baie", "ski-nautique"],
    title: "Ski Nautique Leçon Adulte Mandelieu | Mandelieu WaterSports",
    description: "Découvrez le ski nautique leçon adulte à Mandelieu, Théoule. Venez entre amis, en couple ou en famille profiter du ski nautique à Mandelieu, Théoule",
    accroche: "De l’initiation au perfectionnement : progressez avec un moniteur diplômé d’État.",
    texte: [
      "Le ski nautique procure des sensations de glisse très rapidement car l’activité est très instinctive. Débutant, votre pilote vous donne les clés pour sortir de l’eau ; plus avancé, il vous aide à maîtriser de nouvelles figures.",
      "Dans une ambiance conviviale, de l’initiation au perfectionnement, encadré par un moniteur diplômé d’État.",
    ],
    points: GLISSE_POINTS,
  },

  // --- Packs --------------------------------------------------------------
  {
    slug: "pack-parachute-ascensionnel-bouee-tractee",
    nom: "Pack Parachute Ascensionnel – Bouée Tractée",
    court: "Vol Parachute & Bouée*",
    categorie: "packs",
    prix: 65,
    unite: "par personne",
    age: "Activité pour 2 personnes",
    resaId: "2030",
    note: { valeur: 5, nombre: 889 },
    images: ["pack-parachute-bouee", "carte-pack-bouee", "bouee-tractee-groupe"],
    title: "Pack Parachute Ascensionnel - Bouée Tractée | Mandelieu Théoule",
    description: "Découvrez le parachute ascensionnel et la bouée tractée à Mandelieu, Théoule. Profitez du pack parachute & bouée tractée à Mandelieu Watersports",
    accroche: "Un tour en parachute + un tour en bouée tractée : 30 minutes d’activités au meilleur prix.",
    texte: [
      "Envolez-vous pour de nouvelles sensations et admirez un panorama à 360° entre ciel et mer, puis accrochez-vous bien aux poignées : la bouée tractée va secouer !",
      "Le poids cumulé maximum pour voler en parachute est de 240 kg (jusqu’à 5 personnes). Pack prévu pour 2 personnes.",
    ],
    points: PARACHUTE_POINTS,
    pointsTitre: "Profitez du parachute ascensionnel et de la bouée tractée",
  },
  {
    slug: "parachute-ascensionnel-jet-ski",
    nom: "Pack Parachute Ascensionnel – Jet Ski",
    court: "Vol Parachute & Jet-Ski*",
    categorie: "packs",
    prix: 85,
    unite: "par personne",
    age: "Activité pour 2 personnes",
    resaId: "2009",
    note: { valeur: 5, nombre: 800 },
    bestSeller: true,
    images: ["pack-parachute-jet-ski", "carte-pack-jet-ski", "jet-ski-duo-baie"],
    title: "Pack Parachute Ascensionnel - Jet Ski - Mandelieu WaterSports",
    description: "Découvrez le parachute ascensionnel et le jet ski à Mandelieu, Théoule. Venez entre amis, en couple, en famille profiter du pack parachute & jetski Mandelieu",
    accroche: "Un tour en parachute + 30 minutes de jet ski sans permis : le combo parfait.",
    texte: [
      "Envolez-vous pour de nouvelles sensations et admirez un panorama à 360° entre ciel et mer, puis prenez les commandes d’un jet ski sans permis pour 30 minutes, encadré par un moniteur.",
      "Le poids cumulé maximum pour voler en parachute est de 240 kg. Pack prévu pour 2 personnes.",
    ],
    points: PARACHUTE_POINTS,
    pointsTitre: "Profitez du parachute ascensionnel et du jet ski",
  },
];

export const produit = (slug) => produits.find((p) => p.slug === slug);
export const parCategorie = (c) => produits.filter((p) => p.categorie === c);
